### ISSUE TITLE
How about old MINIX and Linux to MIX

### ISSUE THREAD

**Issue by henoheno** [dspinellis/unix-history-make#1]
Hi. Very interesting work.

It recalls me I had challenged generating cvs repositories about old MINIX and Linux with modified commit-date, and ended the project 10 years ago, before reviving MINIX.

You know they have different directory structures, file transitions, histories and licenses from BSD's,
but if there are another import point (root directory or branch) apart from BSD's,
that may be more a bit comprehensive about Unix histories.

Thanks

---

References:

http://minix-up.osdn.jp/
http://minix-up.osdn.jp/timeline/index.html
http://sourceforge.net/projects/cvsknit/files/TestBuilds/MINIX%20and%20Old%20Linux/
http://www.minix3.org/

**Comment by dspinellis** [comment]
Thank you for your kind words and the links.  For the time being, I'd like to keep the repository focused on systems that are code (rather than just intellectual) descendants of Unix.
