### ISSUE TITLE
Missing files from BSD snapshots

### ISSUE THREAD

**Issue by dspinellis** [dspinellis/unix-history-make#8]
[Reported by @asomers.]
In the unix-history-repo the BSD-SCCS branch looks mostly consistent
with Kirk McKusick's CSRG archive (I haven't checked exhaustively).
However, some of the BSD release branches are missing many files.  For
example, compare https://github.com/dspinellis/unix-history-repo/tree/BSD-4_3_Reno-Snapshot-Development/usr/src/sys/sys with https://www.tuhs.org/cgi-bin/utree.pl?file=4.3BSD-Reno/src/sys/sys.  Could you please check the reconstruction process that produced
those branches?

**Comment by dspinellis** [comment]
Thanks for the feedback!  You're indeed right: the files are missing.  This is done on purpose: I remove from the snapshots the files that are under SCCS control and merge them in later [1].  This results in less faithful snapshot reproduction, but smoother versioning of the SCCS files.

**Comment by asomers** [comment]
So are the XXX-Snapshot-Development branches basically overlays that lay atop BSD-SCCS?  Are the tags, rather than branches, intended to be reflective of the actual historical releases?

**Comment by dspinellis** [comment]
The BSD Development branches are indicated as merges from the SCCS, with the intent being to have the SCCS history be the authoritative one.  See [this figure](https://www.spinellis.gr/pubs/jrnl/2016-EMPSE-unix-history/html/unix-history.html#fig:branches). 

The branches are created to document the importing, so given that they are then merged, their utility is questionable.  Tags should indeed be more useful.
