### ISSUE TITLE
Content weirdly left in .ref-* directories?

### ISSUE THREAD

**Issue by richlowe** [dspinellis/unix-history-make#9]
It's possible I'm missing something hugely important here.

In dspinellis/unix-history-repo at various points, huge swathes of source are, rather than in their normal place, in `.ref-*/...` rooted directories.

I think this is at least in part due to the conflicting branch/tag names. 

 The _branch_ `BSD-4_3_Tahoe-Snapshot-Development` has:
```
; git ls-files '**/n10.c'
.ref-87282391316fa7e8c00b6e73604d26f22f64e105/.ref-BSD-3/usr/src/cmd/troff/n10.c
.ref-87282391316fa7e8c00b6e73604d26f22f64e105/usr/src/local/ditroff/ditroff.okeeffe/n10.c
.ref-87282391316fa7e8c00b6e73604d26f22f64e105/usr/src/local/ditroff/ditroff.okeeffe/troff/n10.c
.ref-87282391316fa7e8c00b6e73604d26f22f64e105/usr/src/old/roff/nroff/n10.c
.ref-BSD-4_3/usr/src/usr.bin/nroff/n10.c
```

The _tag_ `BSD-4_3_Tahoe-Snapshot-Development` has:
```
.ref-BSD-3/usr/src/cmd/troff/n10.c
usr/src/local/ditroff/ditroff.okeeffe/n10.c
usr/src/local/ditroff/ditroff.okeeffe/troff/n10.c
usr/src/old/roff/nroff/n10.c
```

Which is better, but still has that `.ref-BSD-3`

The different revisions involved suggest at least some of them problem might be whether the data was taken from the CSRG archive, or the CSRG SCCS?

```
; git show -s refs/{heads,tags}/BSD-4_3_Tahoe-Snapshot-Development
commit 05e276bc002f942013bc681018e9597b16962115 (origin/BSD-4_3_Tahoe-Snapshot-Development, BSD-4_3_Tahoe-Snapshot-Development)
Author: CSRG <csrg@ucbvax.Berkeley.EDU>
Date:   Fri Jan 5 14:06:44 1990 -0800

    BSD 4_3_Tahoe development
    Work on file usr/dict/spellhist
    
    Synthesized-from: CSRG/cd2/4.3tahoe

commit 87282391316fa7e8c00b6e73604d26f22f64e105 (HEAD, tag: BSD-4_3_Tahoe-Snapshot-Development)
Author: Mike Karels <karels@ucbvax.Berkeley.EDU>
Date:   Mon May 22 16:21:21 1989 -0800

    add dash, range of dates
    
    SCCS-vsn: admin/admin/NIST/NISTreport.03.89 1.2
```

**Comment by dspinellis** [comment]
You're indeed missing something hugely important :-) These directories are temporary and are needed to allow *git blame* to work across snapshots that both modify files and move them around. See Section 3.3 of [this description](https://www.spinellis.gr/pubs/jrnl/2016-EMPSE-unix-history/html/unix-history.html), starting at "An interesting part of the repository representation is how snapshots are imported and linked together".
